// Location: ./crates/cpex-wasm-plugin/src/lib.rs
// Copyright 2025
// SPDX-License-Identifier: Apache-2.0
// Authors: Shriti Priya
//
// CPEX WASM Plugin — Entry point for the WebAssembly plugin component.
//
// Implements the Guest trait generated by wit-bindgen, which the WASM host
// calls via the exported `handle-hook` function. Converts between WIT types
// and native cpex-payload types, delegating to the actual plugin logic.

mod conversions;

// Generate Rust bindings from the WIT world definition.
// This produces the `Guest` trait and all WIT types (MessagePayload, Extensions, etc.)
// that the plugin must implement and use.
wit_bindgen::generate!({
    path: "wit",
    world: "plugin",
    generate_all,
});

use conversions::{native_result_to_wit, wit_context_to_native, wit_extensions_to_native, wit_payload_to_native};

// ---------------------------------------------------------------------------
// Plugin Template
//
// To use a different plugin, change the function call below to point to your
// plugin function in cpex-payload. All plugin functions share the same signature:
//
//   fn(&MessagePayload, &Extensions, &PluginContext) -> PluginResult<MessagePayload>
//
// Example: to use the audit logger instead, replace the identity_check call with:
//   cpex_payload::plugins::audit_logger::audit_log(&native_payload, &native_extensions, &native_ctx)
// ---------------------------------------------------------------------------

struct Plugin;

impl Guest for Plugin {
    /// Entry point called by the WASM host for each hook invocation.
    /// Converts WIT types to native Rust types, delegates to the plugin
    /// logic in cpex-payload, and converts the result back to WIT.
    fn handle_hook(
        payload: MessagePayload,
        extensions: Extensions,
        ctx: PluginContext,
    ) -> PluginResult {
        eprintln!("[WASM] handle_hook called");
        eprintln!("[WASM] payload content parts {:?} : with length {}",payload.message.content, payload.message.content.len());

        // Convert the WIT MessagePayload to native cpex-payload MessagePayload
        let native_payload = wit_payload_to_native(payload);
        eprintln!("[WASM] payload converted to native={:?}",native_payload);

        // Convert the WIT Extensions to native Extensions (wrapped in Arc)
        let native_extensions = wit_extensions_to_native(extensions);
        eprintln!("[WASM] extensions converted to native={:?}",native_extensions);

        // Convert the WIT PluginContext JSON strings to native HashMap-based context
        let native_ctx = wit_context_to_native(ctx);
        eprintln!("[WASM] context converted to native={:?}",native_ctx);

        // Call the plugin logic — swap this line to use a different plugin
        eprintln!("[WASM] calling identity_check...");
        let result = cpex_payload::plugins::identity_checker::identity_check(
            &native_payload,    // the CMF message being processed
            &native_extensions, // security, HTTP, meta, request extensions
            &native_ctx,        // plugin-local and global shared state
        );
        eprintln!("[WASM] identity_check returned: continue_processing={}", result.continue_processing);

        // Convert the native PluginResult back to WIT for the host to consume
        native_result_to_wit(result)
    }
}

// Registers the Plugin struct as the WASM component's exported implementation of the Guest trait
export!(Plugin);
